<?php

return [
    [
        'key'    => 'sales.carriers.mondialrelay',
        'name'   => 'Mondial Relay',
        'info'   => 'Configure Mondial Relay shipping (Point Relais, Locker, Domicile)',
        'sort'   => 3,
        'fields' => [
            [
                'name'          => 'title',
                'title'         => 'Title',
                'type'          => 'text',
                'default'       => 'Mondial Relay',
                'depends'       => 'active:1',
                'validation'    => 'required_if:active,1',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'description',
                'title'         => 'Description',
                'type'          => 'textarea',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'active',
                'title'         => 'Status',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => false,
                'locale_based'  => false,
            ], [
                'name'       => 'code_enseigne',
                'title'      => 'Code Enseigne (API V1 SOAP)',
                'type'       => 'text',
                'depends'    => 'active:1',
                'validation' => 'required_if:active,1',
                'info'       => 'Code Enseigne pour API V1 SOAP',
                'default'    => 'CC23JOIN',
            ], [
                'name'       => 'private_key',
                'title'      => 'Clé Privée (API V1 SOAP)',
                'type'       => 'password',
                'depends'    => 'active:1',
                'validation' => 'required_if:active,1',
                'info'       => 'Clé privée pour signature MD5',
                'default'    => 'QaMz6mTT',
            ], [
                'name'       => 'code_marque',
                'title'      => 'Code Marque (API V1 SOAP)',
                'type'       => 'text',
                'depends'    => 'active:1',
                'validation' => 'required_if:active,1',
                'default'    => 'CC',
            ], [
                'name'    => 'api_url',
                'title'   => 'URL API V1 (SOAP)',
                'type'    => 'text',
                'default' => 'https://api.mondialrelay.com/WebService.asmx',
            ], [
                'name'       => 'api_v2_url',
                'title'      => 'URL API V2 (REST)',
                'type'       => 'text',
                'default'    => 'https://connect-api.mondialrelay.com/api/shipment',
                'depends'    => 'active:1',
            ], [
                'name'       => 'api_v2_login',
                'title'      => 'Login API V2 (REST)',
                'type'       => 'text',
                'depends'    => 'active:1',
                'validation' => 'required_if:active,1',
                'info'       => 'Login pour API V2 REST',
                'default'    => 'CC23JOIN@business-api.mondialrelay.com',
            ], [
                'name'       => 'api_v2_password',
                'title'      => 'Password API V2 (REST)',
                'type'       => 'password',
                'depends'    => 'active:1',
                'validation' => 'required_if:active,1',
                'info'       => 'Mot de passe pour API V2 REST',
                'default'    => '-jTqc7ps1>wAbBYuh3p3',
            ], [
                'name'       => 'api_v2_brand_id',
                'title'      => 'Brand ID API V2 (REST)',
                'type'       => 'text',
                'depends'    => 'active:1',
                'validation' => 'required_if:active,1',
                'default'    => 'CC23JOIN',
            ], [
                'name'    => 'enable_point_relais',
                'title'   => 'Activer Points Relais',
                'type'    => 'boolean',
                'default' => true,
            ], [
                'name'    => 'enable_locker',
                'title'   => 'Activer Lockers',
                'type'    => 'boolean',
                'default' => true,
            ], [
                'name'    => 'enable_domicile',
                'title'   => 'Activer Livraison Domicile',
                'type'    => 'boolean',
                'default' => false,
                'info'    => 'Livraison domicile (code service HOM)',
            ], [
                'name'    => 'label_format',
                'title'   => 'Format d\'étiquette',
                'type'    => 'select',
                'default' => '10x15',
                'options' => [
                    ['title' => '10x15 cm', 'value' => '10x15'],
                    ['title' => 'A4', 'value' => 'A4'],
                    ['title' => 'A5', 'value' => 'A5'],
                ],
            ],
        ],
    ],
];
